### ISSUE TITLE
Logo : Meaningful Edi Logo

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#10]
as we know that :

> An application or commit, should and must have its *unique*, *solid* and *meaningful* name.  along with meaningful icon. - J. Verdeburg

I am trying to relate Edi with the Icon, and return an NullReferenceException 😄 , can you tell the audience what is Edi icon meaning, then they will likely try the app.

**Comment by Dirkster99** [comment]
The icon is just an icon that I designed according to a close friends dog - nothing more - I am borred by another app with another pen and paper icon - but you can suggest other icons if you think its that simple :-)
