### ISSUE TITLE
Switching to Generic Themes does not work...

### ISSUE THREAD

**Issue by Dirkster99** [Dirkster99/Edi#14]
Start Edi and switch theme to View > Themes > Generic
Bugs

1. The AvalonEdit Editor does not show in Generics Theme
2. The AvalonDock component sometimes reloads a UML file multiple times
    which can cause the editor to slow down since its busy managing 100's of files when switching themes a   few time ;-(

**Comment by rasyidf** [comment]
Still searching the bug.

**Comment by Dirkster99** [comment]
Don't worry about it if you cannot find it either we might get to it in the end when I rework the theming...

**Comment by Dirkster99** [comment]
I found the solution for this problem

**Comment by Dirkster99** [comment]
This commit contains the fix:
https://github.com/Dirkster99/Edi/commit/b8d1c763f1c9b1fbd9afc30c0da04275bd3093b5

The "/Edi.Themes;component/MetroLight/EdiAvalonEdit.xaml", has to be loaded to ensure that AvalonEdit Editor is available.
