### ISSUE TITLE
Review Nuget integration

### ISSUE THREAD

**Issue by Dirkster99** [Dirkster99/Edi#16]
I have put 2 components into NuGet:
https://github.com/Dirkster99/DropDownButtonLib
https://github.com/Dirkster99/UserNotifications

...and added the MsgBox project with a dependency to the UserNotifications package in NuGet:
https://github.com/Dirkster99/MsgBox

Would you have a minute and review the MsgBox project to make sure I added the NuGet dependency correctly? I would then continue to add MsgBox to Nuget and add the reference into Edi etc...

**Comment by rasyidf** [comment]
Are you sure to put all in separate project? 
maybe we get the benefit by cleaning the solution and faster loading, but for versioning it will be difficult to maintain.

**Comment by rasyidf** [comment]
All Good, i just cant see where the package.json located

**Comment by Dirkster99** [comment]
Yes I am sure its better to seperate controls into projects because I am starting to loose the overview and already had some version/API mismatches to clean out for the MsgBox Contrl - so I am thinking of re-designing controls for a more consistent look and feel such that they will fit into the MLib library which I want to use as the theming library in the end... but that some way to go and won't be happening anytime soon. Thanks for looking at this :-)

**Comment by Dirkster99** [comment]
I guess I do not want extra problems getting generated with that nuget approach and go unnoticed. So its fine by me if you cannot See an additional Problem either.

One Problem I see now is that depended packages are only available for execution (in the Edi.exe folder) if I installed the package for the Edi project AS well :-( Do you know a better solution besides build events to resolve this more straightforward?

**Comment by Dirkster99** [comment]
I saw on a youtube video about msbuild that project.json is still supported but no longer required because the XML project structure has advantages that are judged as more important than json which has its limitations too ... I included an automatic build via https://appveyor.com/ and the result is looking good so I guess the nuget integration is good enough :-)
