### ISSUE TITLE
Add mini UML Some Modernization

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#30]
I know if MiniUML made as simple as possible. but the idea of changing it more modern. and immersive with the application itself.

for example a color, like this : 

![7026 image12](https://user-images.githubusercontent.com/28984914/34114368-33d315d0-e445-11e7-9c54-15e393b719d6.png)

**Comment by Dirkster99** [comment]
thats a great idea - I would not mind if anyone would contribute a design like that at all :-)
