### ISSUE TITLE
Replacing ResX Localization with Json/XML/Csv

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#7]
We can see that Edi uses ResX Localization that it must be compiled to get the language available.

I think [this](https://gist.github.com/Elsensee/9370857) approach can be used, or we could improve it with Json / XML. so that users can add their own translation without having VS and the source code.

**Comment by Dirkster99** [comment]
I agree - Json/XML sounds more trustworthy than CSV in my ears :-) but I am not sure how this is supposed to work when you load a static string in an XAML View how does it get looked up at runtime and is being translated correctly.

Do you know a good reference project to better understand localization based on Json/XAML?

**Comment by rasyidf** [comment]
Currently I am working on UFSJ (File Splitter and Joiner) that uses Language pack like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<UFSJ>
  <Language Name="English" LCID="1033" Local="United States">
    <Author Name ="Rasyid" Contact = "http://rasyidufa.github.io/UFSJ/" />
  </Language>

  <!--Add Language Window-->
```

and it's run smoothly

**Comment by rasyidf** [comment]
![a](https://user-images.githubusercontent.com/28984914/26896353-9d5f8cd0-4bee-11e7-9e17-64822b373a5e.gif)

It can translate language without restarting.
see last frame, the .gifs actually showing theming support.. just re-pick..

**Comment by Dirkster99** [comment]
yes, it looks good to me - I just need a complete demo project **with code** :-) to really understand how it works...

**Comment by rasyidf** [comment]
Soon after my Exam. :)  I'll try to simplify the code.

**Comment by Dirkster99** [comment]
I see you mean this project:
https://github.com/RasyidUFA/UFSJ

I can have a look at it - no problem - its just confusing because you have 2 github logins and there was no url so for :-)

**Comment by Dirkster99** [comment]
Here is a demo WPF project called [SettingsModelWPFDemo](https://github.com/Dirkster99/SettingsModel/tree/master/1.0/Demos_Tests/SettingsModelWPFDemo) + [Documentation](https://github.com/Dirkster99/SettingsModel/blob/master/1.0/01_docs/Documentation.md)

which is also translated with resx files:
- When you have the time - do you think you could develop this into a 2.0 version that uses Json / XML?

This would allow us to have both versions side by side and compare their function on a much smaller and more simplified scale :-)

**Comment by rasyidf** [comment]
I've pushed new repo that uses my framework, Json and XML. 
[Here](https://github.com/rasyidf/UFA.Localization)

as you've said, I'm working on 2.0 version.
