### ISSUE TITLE
Naming Issue : consider to describe what and why you choose Edi as name.

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#9]
I am noticing from some fellow friends, that the name Edi is bit confusing, they always ask, what is Edi stand for. 
I give them my prediction, 

> "EDI is reversed IDE" 

or

> Entity Development Interface

and something else. But, when i asked my mentors, he tells me that 

> An application or commit, should and must have its *unique*, *solid* and *meaningful* name.  along with meaningful icon. - J. Verdeburg

so this will be funny but big issue, why the name is *Edi*

**Comment by Dirkster99** [comment]
Edi ist just a name - not every name has to mean something in the way that it spells out to something in particular - you can take it short for editor or editing or reverse for ide or ... Google for instance is also just a name and does not mean more than google but is ok for everyone ...
